


module.exports = {
  info: [
    ['Upgrades', [
      {name:"30 Deku Nuts", id:"30-deku-nuts", difficulty:1},
      {name:"Bomb Bag (30)", id:"bomb-bag-30-", difficulty:1},
      {name:"Bullet Bag (40)", id:"bullet-bag-40-", difficulty:7},
      {name:"Bullet Bag (50)", id:"bullet-bag-50-", difficulty:1},
      {name:"Exactly 20 Deku Sticks", id:"exactly-20-deku-sticks", difficulty:1},
      {name:"Exactly 30 Deku Sticks", id:"exactly-30-deku-sticks", difficulty:2},
      {name:"Quiver (40)", id:"quiver-40-", difficulty:2},
      {name:"Silver Scale", id:"silver-scale", difficulty:4},
      {name:"Giant's Wallet", id:"giant-s-wallet", difficulty:8},
      {name:"Golden Gauntlets", id:"golden-gauntlets", difficulty:8},
      {name:"Bronze Gauntlets", id:"bronze-gauntlets", difficulty:11},
      {name:"Silver Gauntlets", id:"silver-gauntlets", difficulty:15},
      {name:"Blue Gauntlets", id:"blue-gauntlets", difficulty:17},
      {name:"Goron Bracelet", id:"goron-bracelet", difficulty:21},
      {name:"Green Gauntlets", id:"green-gauntlets", difficulty:24},
      {name:"500 Rupees", id:"500-rupees", difficulty:11},
      {name:"Stone of Agony", id:"stone-of-agony", difficulty:11},
      {name:"Quiver (50)", id:"quiver-50-", difficulty:19},
    ]],
    ['Bottles', [
      {name:"Bottled Fairy", id:"bottled-fairy", difficulty:1},
      {name:"Blue Fire", id:"blue-fire", difficulty:5},
      {name:"Blue Potion", id:"blue-potion", difficulty:6},
      {name:"Fill all 4 Bottle Slots", id:"fill-all-4-bottle-slots", difficulty:7},
      {name:"Milk", id:"milk", difficulty:8},
    ]],
    ['Defeat', [
      {name:"Defeat a Skull Kid", id:"defeat-a-skull-kid", difficulty:1},
      {name:"Defeat King Dodongo", id:"defeat-king-dodongo", difficulty:5},
      {name:"Defeat a White Wolfos", id:"defeat-a-white-wolfos", difficulty:6},
      {name:"Defeat Phantom Ganon", id:"defeat-phantom-ganon", difficulty:6},
      {name:"Defeat all Lizalfos in Dodongo's Cavern", id:"defeat-all-lizalfos-in-dodongo-s-cavern", difficulty:6},
      {name:"Defeat Morpha", id:"defeat-morpha", difficulty:8},
      {name:"Defeat Queen Gohma", id:"defeat-queen-gohma", difficulty:7},
      {name:"Defeat Dark Link", id:"defeat-dark-link", difficulty:9},
      {name:"Defeat Big Octo", id:"defeat-big-octo", difficulty:10},
      {name:"Defeat Amy (Green Poe)", id:"defeat-amy-green-poe-", difficulty:12},
      {name:"Defeat Bongo-Bongo", id:"defeat-bongo-bongo", difficulty:12},
      {name:"Defeat both Flare Dancers", id:"defeat-both-flare-dancers", difficulty:14},
      {name:"Defeat Barinade", id:"defeat-barinade", difficulty:15},
      {name:"Defeat Nabooru-Knuckle", id:"defeat-nabooru-knuckle", difficulty:17},
      {name:"Defeat Volvagia", id:"defeat-volvagia", difficulty:17},
      {name:"Defeat Meg (purple Poe)", id:"defeat-meg-purple-poe-", difficulty:19},
      {name:"Defeat 4 Different Iron Knuckles", id:"defeat-4-different-iron-knuckles", difficulty:23},

      {name:"Beat the Deku Tree", id:"beat-the-deku-tree", difficulty:7},
      {name:"Beat the Forest Temple", id:"beat-the-forest-temple", difficulty:7},
      {name:"Beat Dodongo's Cavern", id:"beat-dodongo-s-cavern", difficulty:8},
      {name:"Beat the Water Temple", id:"beat-the-water-temple", difficulty:8},
      {name:"Beat the Shadow Temple", id:"beat-the-shadow-temple", difficulty:12},
      {name:"Beat Jabu-Jabu's Belly", id:"beat-jabu-jabu-s-belly", difficulty:17},
      {name:"Beat the Fire Temple", id:"beat-the-fire-temple", difficulty:18},

      {name:"Forest Medallion", id:"forest-medallion", difficulty:7},
      {name:"Water Medallion", id:"water-medallion", difficulty:9},
      {name:"Fire Medallion", id:"fire-medallion", difficulty:19},

      {name:"Get to the end of Fire Trial", id:"get-to-the-end-of-fire-trial", difficulty:10},
      {name:"Get to the end of Light Trial", id:"get-to-the-end-of-light-trial", difficulty:11},
      {name:"Get to the end of Spirit Trial", id:"get-to-the-end-of-spirit-trial", difficulty:20},
      {name:"Get to the end of Water Trial", id:"get-to-the-end-of-water-trial", difficulty:20},
      {name:"Get to the end of Shadow Trial", id:"get-to-the-end-of-shadow-trial", difficulty:22},
    ]],
    ['Equipment', [
      {name:"Giant's Knife", id:"giant-s-knife", difficulty:1},
      {name:"Goron Tunic", id:"goron-tunic", difficulty:2},
      {name:"Zora Tunic", id:"zora-tunic", difficulty:2},
      {name:"3 Tunics", id:"3-tunics", difficulty:4},
      {name:"3 Swords & 3 Tunics", id:"3-swords-3-tunics", difficulty:6},
      {name:"Iron Boots", id:"iron-boots", difficulty:7},
      {name:"3 Boots", id:"3-boots", difficulty:11},
      {name:"3 Swords & 3 Boots", id:"3-swords-3-boots", difficulty:13},
      {name:"3 Shields", id:"3-shields", difficulty:16},
      {name:"3 Tunics & 3 Boots", id:"3-tunics-3-boots", difficulty:16},
      {name:"3 Swords & 3 Shields", id:"3-swords-3-shields", difficulty:17},
      {name:"3 Shields & 3 Boots", id:"3-shields-3-boots", difficulty:23},
      {name:"3 Shields & 3 Tunics", id:"3-shields-3-tunics", difficulty:20},
    ]],
    ['Inventory', [
      {name:"Lens of Truth", id:"lens-of-truth", difficulty:1},
      {name:"5 Magic Beans", id:"5-magic-beans", difficulty:3},
      {name:"Fairy Slingshot", id:"fairy-slingshot", difficulty:5},
      {name:"Ice Arrows", id:"ice-arrows", difficulty:5},
      {name:"Ruto's Letter", id:"ruto-s-letter", difficulty:6},
      {name:"Longshot", id:"longshot", difficulty:9},
      {name:"Boomerang", id:"boomerang", difficulty:11},
      {name:"Fire Arrows", id:"fire-arrows", difficulty:11},
      {name:"Fairy Bow", id:"fairy-bow", difficulty:12},
      {name:"Keaton Mask", id:"keaton-mask", difficulty:14},
      {name:"Megaton Hammer", id:"megaton-hammer", difficulty:14},
      {name:"Mirror Shield", id:"mirror-shield", difficulty:15},
      {name:"Light Arrows", id:"light-arrows", difficulty:18},
      {name:"Spooky Mask", id:"spooky-mask", difficulty:18},
    ]],
    ['Dungeons', [
      {name:"Map & Compass in Bottom of the Well", id:"map-compass-in-bottom-of-the-well", difficulty:1},
      {name:"Map & Compass in Dodongo's Cavern", id:"map-compass-in-dodongo-s-cavern", difficulty:3},
      {name:"Map & Compass in Deku Tree", id:"map-compass-in-deku-tree", difficulty:5},
      {name:"Map & Compass in Ice Cavern", id:"map-compass-in-ice-cavern", difficulty:6},
      {name:"Map & Compass in Shadow Temple", id:"map-compass-in-shadow-temple", difficulty:7},
      {name:"Map & Compass in Water Temple", id:"map-compass-in-water-temple", difficulty:9},
      {name:"Map & Compass in Fire Temple", id:"map-compass-in-fire-temple", difficulty:12},
      {name:"Map & Compass in Jabu-Jabu", id:"map-compass-in-jabu-jabu", difficulty:13},
      {name:"Map & Compass in Forest Temple", id:"map-compass-in-forest-temple", difficulty:15},
      {name:"Map & Compass in Spirit Temple", id:"map-compass-in-spirit-temple", difficulty:24},

      {name:"4 Maps", id:"4-maps", difficulty:6},
      {name:"5 Maps", id:"5-maps", difficulty:10},
      {name:"6 Maps", id:"6-maps", difficulty:16},
      {name:"7 Maps", id:"7-maps", difficulty:21},
      {name:"4 Compasses", id:"4-compasses", difficulty:9},
      {name:"5 Compasses", id:"5-compasses", difficulty:15},
      {name:"6 Compasses", id:"6-compasses", difficulty:20},
      {name:"7 Compasses", id:"7-compasses", difficulty:24},

      {name:"Fire Temple Boss Key", id:"fire-temple-boss-key", difficulty:3},
      {name:"Ganon's Castle Boss Key", id:"ganon-s-castle-boss-key", difficulty:6},
      {name:"Water Temple Boss Key", id:"water-temple-boss-key", difficulty:6},
      {name:"Shadow Temple Boss Key", id:"shadow-temple-boss-key", difficulty:12},
      {name:"Forest Temple Boss Key", id:"forest-temple-boss-key", difficulty:14},
      {name:"Spirit Temple Boss Key", id:"spirit-temple-boss-key", difficulty:19},
      {name:"2 Boss Keys", id:"2-boss-keys", difficulty:6},
      {name:"3 Boss Keys", id:"3-boss-keys", difficulty:14},

      {name:"Free all 9 Gorons in Fire Temple", id:"free-all-9-gorons-in-fire-temple", difficulty:20},
      {name:"3 Unused Keys in Gerudo Training Grounds", id:"3-unused-keys-in-gerudo-training-grounds", difficulty:6},
      {name:"4 Unused Keys in Gerudo Training Grounds", id:"4-unused-keys-in-gerudo-training-grounds", difficulty:7},
      {name:"5 Unused Keys in Gerudo Training Grounds", id:"5-unused-keys-in-gerudo-training-grounds", difficulty:8},
      {name:"6 Unused Keys in Gerudo Training Grounds", id:"6-unused-keys-in-gerudo-training-grounds", difficulty:9},
      {name:"7 Different Unused Keys in Gerudo Training Grounds", id:"7-different-unused-keys-in-gerudo-training-grounds", difficulty:12},
      {name:"8 Different Unused Keys in Gerudo Training Grounds", id:"8-different-unused-keys-in-gerudo-training-grounds", difficulty:14},

      {name:"4 Unused Keys in Forest Temple", id:"4-unused-keys-in-forest-temple", difficulty:9},
      {name:"Obtain all 8 Small Keys in Fire Temple", id:"obtain-all-8-small-keys-in-fire-temple", difficulty:13},
      {name:"Obtain all 5 Small Keys in Forest Temple", id:"obtain-all-5-small-keys-in-forest-temple", difficulty:17},
      {name:"Obtain all 5 Small Keys in Shadow Temple", id:"obtain-all-5-small-keys-in-shadow-temple", difficulty:20},
      {name:"1 Unused Small Key in each Adult Dungeon", id:"1-unused-small-key-in-each-adult-dungeon", difficulty:22},
    ]],
    ['Songs', [
      {name:"Bolero of Fire", id:"bolero-of-fire", difficulty:2},
      {name:"Minuet of Forest", id:"minuet-of-forest", difficulty:2},
      {name:"3 Songs", id:"3-songs", difficulty:6},
      {name:"4 Songs", id:"4-songs", difficulty:6},
      {name:"6 Songs", id:"6-songs", difficulty:7},
      {name:"Epona's Song", id:"epona-s-song", difficulty:9},
      {name:"7 Songs", id:"7-songs", difficulty:10},
      {name:"Requiem of Spirit", id:"requiem-of-spirit", difficulty:10},
      {name:"9 Songs", id:"9-songs", difficulty:15},
      {name:"Saria's Song", id:"saria-s-song", difficulty:17},
    ]],
    ['Hearts', [
      {name:"5 Hearts", id:"5-hearts", difficulty:3},
      {name:"6 Hearts", id:"6-hearts", difficulty:8},
      {name:"7 Hearts", id:"7-hearts", difficulty:11},
      {name:"8 Hearts", id:"8-hearts", difficulty:17},
      {name:"9 Hearts", id:"9-hearts", difficulty:23},
      {name:"Both HPs in Death Mountain Crater", id:"both-hps-in-death-mountain-crater", difficulty:3},
      {name:"Lon Lon Ranch HP", id:"lon-lon-ranch-hp", difficulty:3},
      {name:"Both Gerudo Valley HPs", id:"both-gerudo-valley-hps", difficulty:5},
      {name:"Ice Cavern HP", id:"ice-cavern-hp", difficulty:5},
      {name:"37th Heart Piece (Child Fortress)", id:"37th-heart-piece-child-fortress-", difficulty:8},
      {name:"8 Songs", id:"8-songs", difficulty:11},
      {name:"5 Zora area HPs", id:"5-zora-area-hps", difficulty:12},
      {name:"Frog's HP", id:"frog-s-hp", difficulty:17},
      {name:"Both HPs in Lost Woods", id:"both-hps-in-lost-woods", difficulty:23},
    ]],
    ['Activities', [
      {name:"Plant bean in Death Mountain Crater", id:"plant-bean-in-death-mountain-crater", difficulty:6},
      {name:"Cow in House", id:"cow-in-house", difficulty:6},
      {name:"Win Bombchu Bowling Prize", id:"win-bombchu-bowling-prize", difficulty:9},
      {name:"Gerudo's Card", id:"gerudo-s-card", difficulty:12},
      {name:"Get Bombchu chest in Spirit Temple", id:"get-bombchu-chest-in-spirit-temple", difficulty:16},
    ]],
    ['Skulltulas', [
      {name:"All 3 Skulltulas in Bottom of the Well", id:"all-3-skulltulas-in-bottom-of-the-well", difficulty:5},
      {name:"All 3 Kokiri Forest area Skulltulas", id:"all-3-kokiri-forest-area-skulltulas", difficulty:6},
      {name:"All 3 Skulltulas in Ice Cavern", id:"all-3-skulltulas-in-ice-cavern", difficulty:6},
      {name:"Both Gerudo's Fortress area Skulltulas", id:"both-gerudo-s-fortress-area-skulltulas", difficulty:6},
      {name:"3 Lake Hylia Skulltulas", id:"3-lake-hylia-skulltulas", difficulty:7},
      {name:"All 4 Lost Woods area Skulltulas", id:"all-4-lost-woods-area-skulltulas", difficulty:7},
      {name:"All 5 Skulltulas in Dodongo's Cavern", id:"all-5-skulltulas-in-dodongo-s-cavern", difficulty:8},
      {name:"All 8 Kakariko area Skulltulas", id:"all-8-kakariko-area-skulltulas", difficulty:8},
      {name:"15 Different Skulltulas", id:"15-different-skulltulas", difficulty:9},
      {name:"All 4 Gerudo Valley area Skulltulas", id:"all-4-gerudo-valley-area-skulltulas", difficulty:9},
      {name:"All 5 Skulltulas in Forest Temple", id:"all-5-skulltulas-in-forest-temple", difficulty:9},
      {name:"All 4 Lon-Lon Ranch area Skulltulas", id:"all-4-lon-lon-ranch-area-skulltulas", difficulty:10},
      {name:"All 4 Skulltulas in Deku Tree", id:"all-4-skulltulas-in-deku-tree", difficulty:10},
      {name:"All 4 Skulltulas in Jabu-Jabu", id:"all-4-skulltulas-in-jabu-jabu", difficulty:10},
      {name:"Both Hyrule Field area Skulltulas", id:"both-hyrule-field-area-skulltulas", difficulty:10},
      {name:"All 8 Death Mountain area Skulltulas", id:"all-8-death-mountain-area-skulltulas", difficulty:11},
      {name:"3 Skulltulas in Water Temple", id:"3-skulltulas-in-water-temple", difficulty:13},
      {name:"4 Skulltulas in Shadow Temple", id:"4-skulltulas-in-shadow-temple", difficulty:13},
      {name:"All 8 Zora's Domain area Skulltulas", id:"all-8-zora-s-domain-area-skulltulas", difficulty:14},
      {name:"All 5 Skulltulas in Fire Temple", id:"all-5-skulltulas-in-fire-temple", difficulty:15},
      {name:"All 4 Wasteland/ Colossus area Skulltulas", id:"all-4-wasteland-colossus-area-skulltulas", difficulty:16},
      {name:"All 5 Lake Hylia Skulltulas", id:"all-5-lake-hylia-skulltulas", difficulty:17},
      {name:"All 5 Skulltulas in Spirit Temple", id:"all-5-skulltulas-in-spirit-temple", difficulty:20},
      {name:"All 5 Skulltulas in Shadow Temple", id:"all-5-skulltulas-in-shadow-temple", difficulty:22},
      {name:"All 5 Skulltulas in Water Temple", id:"all-5-skulltulas-in-water-temple", difficulty:22},
      {name:"All 4 Market area Skulltulas", id:"all-4-market-area-skulltulas", difficulty:23},
      {name:"1 Skulltula from each Child Dungeon", id:"1-skulltula-from-each-child-dungeon", difficulty:14},
      {name:"1 Skulltula from each Adult Dungeon", id:"1-skulltula-from-each-adult-dungeon", difficulty:24},
    ]],
    ['Magic', [
      {name:"Double Defense", id:"double-defense", difficulty:13},
      {name:"Double Magic", id:"double-magic", difficulty:13},
      {name:"Farore's Wind", id:"farore-s-wind", difficulty:15},
      {name:"Din's Fire", id:"din-s-fire", difficulty:19},
      {name:"Nayru's Love", id:"nayru-s-love", difficulty:21},
    ]],
  ]
};
